// In jenkins-repo/Jenkinsfile
pipeline {
    agent any
    // This block tells Jenkins to accept a parameter when the build is triggered.
    parameters {
        string(name: 'JSON_PAYLOAD', defaultValue: '{}', description: 'JSON data from the frontend')
    }
    stages {
        stage('Generate Terraform Code') {
            steps {
                dir('jenkins-repo') {
                    // This command takes the JSON parameter and "pipes" it into your Python script.
                    sh "echo '${params.JSON_PAYLOAD}' | python3 main.py"
                }
            }
        }
        // The "Commit to Git" stage is no longer needed and should be removed.
        stage('Deploy with Terraform') {
            steps {
                dir('jenkins-repo') {
                    withCredentials([aws(credentialsId: 'aws-creds')]) {
                        sh 'terraform init'
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }
    }
}
